### PR TITLE
Fix pre-commit

### PR DESCRIPTION
**Pull request by dstansby**
This fixes all the pre-commit errors. I've also added pre-commit.ci to the CI (hopefully) so we have a pre-commit check continuously run. Happy to not do this if there's voices against pre-commit.ci?

### CODE REVIEW

**Review by d-v-b — APPROVED** [review]
lgtm

**Comment by d-v-b** [comment]
feel free to merge whenever!

**Comment by dstansby** [comment]
👍  (btw I am very pro reviewer merges by default, so always feel free to merge my PRs if you approve of them)

**Comment by d-v-b** [comment]
> 👍 (btw I am very pro reviewer merges by default, so always feel free to merge my PRs if you approve of them)

will do

**Pull request merged**
